version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: snippetDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
